st.title("Student Management")
st.sidebar.title("Fee Management")
         st.sidebar.subheader("Add Student")
         rollnumber= st.sidebar.number_input("Rollnumber")
name = st.sidebar.number_input("Name")
fees = st.sidebar.number_input("Fees")
add = st.sidebar.button("Add")
